-- ================================================================
-- SCRIPT DE CREACION DE TABLAS PARA proyecto_cobol
-- Generado a partir de los Copybooks y DBIO (.sqb)
-- ================================================================

CREATE DATABASE IF NOT EXISTS proyecto_cobol;
USE proyecto_cobol;

-- 1. TABLA: clientes (Referencia: CUSMREC.CPY / DBIOCUSM.sqb)
CREATE TABLE IF NOT EXISTS clientes (
    ID_CLIENTE INT(8) PRIMARY KEY,
    TIPO_DOC VARCHAR(3),
    DOC_CLIENTE VARCHAR(12),
    FECHA_ALTA DATE,
    NOMBRE_CLIENTE VARCHAR(25),
    APELLIDOS_CLIENTE VARCHAR(25),
    DIRECCION_CLIENTE VARCHAR(45),
    TELEF_CLIENTE VARCHAR(12),
    EMAIL_CLIENTE VARCHAR(40),
    TARJETA TINYINT(1),
    CREDITO TINYINT(1),
    HIPOTECA TINYINT(1),
    CTA_ACTIVA TINYINT(1),
    FECHA_CIERRE DATE,
    SALDO_CLIENTE DECIMAL(12,2)
);

-- 2. TABLA: TARJETAS (Referencia: TARJREC.CPY / DBIOTARJ.sqb)
CREATE TABLE IF NOT EXISTS TARJETAS (
    ID_CLIENTE INT(8),
    NRO_TARJETA VARCHAR(16),
    FECHA_EMISION DATE,
    FECHA_VENCIMIENTO DATE,
    LIMITE_TARJETA DECIMAL(12,2),
    ACUM_MES DECIMAL(12,2),
    LIQUIDACION_MES DECIMAL(12,2),
    ESTADO CHAR(1),
    PRIMARY KEY (ID_CLIENTE, NRO_TARJETA)
);

-- 3. TABLA: ctactes (Referencia: INVMREC.CPY / DBIOINVM.sqb)
CREATE TABLE IF NOT EXISTS ctactes (
    ID_CLIENTE INT(8) PRIMARY KEY,
    COD_ULT_MOV INT(2),
    FECHA_ULT_MOV DATE,
    IMPORTE_MOV DECIMAL(12,2),
    SALDO_ACTUAL DECIMAL(12,2)
);

-- 4. TABLA: HIPOTECAS (Referencia: BORMREC.CPY)
CREATE TABLE IF NOT EXISTS HIPOTECAS (
    ID_HIPOTECA INT(9) PRIMARY KEY,
    ID_CLIENTE INT(9),
    FECHA_INICIO DATE,
    MONTO_ORIGINAL DECIMAL(15,2),
    TASA_INTERES DECIMAL(7,4),
    SALDO_ACTUAL DECIMAL(15,2),
    FECHA_VENCTO DATE,
    DIA_PAGO INT(2),
    ESTADO VARCHAR(20)
);

-- 5. TABLA: COD_MOVIMIENTOS (Catálogo estándar)
CREATE TABLE IF NOT EXISTS COD_MOVIMIENTOS (
    CODIGO INT(2) PRIMARY KEY,
    DESCRIPCION VARCHAR(30),
    TIPO_AFECTACION CHAR(1) -- '+' o '-'
);

-- 6. TABLA: INDICADORES (Catálogo estándar)
CREATE TABLE IF NOT EXISTS INDICADORES (
    CODIGO VARCHAR(10) PRIMARY KEY,
    VALOR DECIMAL(10,4),
    DESCRIPCION VARCHAR(50)
);
