/* Generated by           cobc 2.0.0 */
/* Generated from         C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
/* Generated at           may 18 2026 16:55:41 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobc.exe -C --save-temps=C:\Users\Alison\AppData\Local\Temp\cobtmp -I C:\Users\Alison\Desktop\proyecto_cobol\src\copies C:\Users\Alison\Desktop\proyecto_cobol\src\mainline\TC0000.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
	{'$', 1},
	{'Z', 3},
	{',', 1},
	{'Z', 3},
	{',', 1},
	{'Z', 2},
	{'9', 1},
	{'.', 1},
	{'9', 2},
	{'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x10,   3,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   8,   0, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x12,  12,   2, 0x0001, NULL};
static const cob_field_attr a_6 =	{0x10,   4,   0, 0x0000, NULL};
static const cob_field_attr a_7 =	{0x10,   2,   0, 0x0000, NULL};
static const cob_field_attr a_8 =	{0x24,  11,   2, 0x0000, p_1};
static const cob_field_attr a_9 =	{0x10,   5,   0, 0x0000, NULL};
static const cob_field_attr a_10 =	{0x10,   1,   0, 0x0000, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1	= {17, (cob_u8_ptr)"Opcion no valida.", &a_1};
static const cob_field c_2	= {32, (cob_u8_ptr)"=== EMISION DE TARJETA NUEVA ===", &a_1};
static const cob_field c_3	= {44, (cob_u8_ptr)"ERROR: Cliente inactivo. No se puede operar.", &a_1};
static const cob_field c_4	= {30, (cob_u8_ptr)"Presione ENTER para continuar.", &a_1};
static const cob_field c_5	= {39, (cob_u8_ptr)"RECHAZO: Score crediticio insuficiente.", &a_1};
static const cob_field c_6	= {13, (cob_u8_ptr)"Score actual:", &a_1};
static const cob_field c_7	= {29, (cob_u8_ptr)"Minimo requerido: 450 puntos.", &a_1};
static const cob_field c_8	= {46, (cob_u8_ptr)"ERROR: El cliente ya posee una tarjeta activa.", &a_1};
static const cob_field c_9	= {40, (cob_u8_ptr)"No se pueden emitir tarjetas duplicadas.", &a_1};
static const cob_field c_10	= {32, (cob_u8_ptr)"ID cuenta para debito de pagos: ", &a_1};
static const cob_field c_11	= {29, (cob_u8_ptr)"ERROR: ID de cuenta invalido.", &a_1};
static const cob_field c_12	= {42, (cob_u8_ptr)"ERROR: Cuenta no encontrada en el sistema.", &a_1};
static const cob_field c_13	= {45, (cob_u8_ptr)"ERROR: La cuenta seleccionada no esta activa.", &a_1};
static const cob_field c_14	= {40, (cob_u8_ptr)"ERROR: No se permite cuenta hipotecaria.", &a_1};
static const cob_field c_15	= {30, (cob_u8_ptr)"Cupo a otorgar (ej: 2000.00): ", &a_1};
static const cob_field c_16	= {20, (cob_u8_ptr)"Operacion cancelada.", &a_1};
static const cob_field c_17	= {37, (cob_u8_ptr)"ERROR: El cupo debe ser mayor a cero.", &a_1};
static const cob_field c_18	= {1, (cob_u8_ptr)"-", &a_1};
static const cob_field c_19	= {36, (cob_u8_ptr)">>> Tarjeta emitida exitosamente <<<", &a_1};
static const cob_field c_20	= {9, (cob_u8_ptr)"Numero : ", &a_1};
static const cob_field c_21	= {9, (cob_u8_ptr)"Vencto : ", &a_1};
static const cob_field c_22	= {9, (cob_u8_ptr)"Cupo   : ", &a_1};
static const cob_field c_23	= {42, (cob_u8_ptr)"ERROR: El cliente ya tiene tarjeta activa.", &a_1};
static const cob_field c_24	= {27, (cob_u8_ptr)"=== CONSULTA DE TARJETA ===", &a_1};
static const cob_field c_25	= {39, (cob_u8_ptr)"El cliente no tiene tarjeta registrada.", &a_1};
static const cob_field c_26	= {42, (cob_u8_ptr)"------------------------------------------", &a_1};
static const cob_field c_27	= {10, (cob_u8_ptr)"Numero  : ", &a_1};
static const cob_field c_28	= {10, (cob_u8_ptr)"Estado  : ", &a_1};
static const cob_field c_29	= {10, (cob_u8_ptr)"Emision : ", &a_1};
static const cob_field c_30	= {10, (cob_u8_ptr)"Vencto  : ", &a_1};
static const cob_field c_31	= {15, (cob_u8_ptr)"Cupo Total   : ", &a_1};
static const cob_field c_32	= {15, (cob_u8_ptr)"Deuda Actual : ", &a_1};
static const cob_field c_33	= {15, (cob_u8_ptr)"Cupo Libre   : ", &a_1};
static const cob_field c_34	= {42, (cob_u8_ptr)"=== CONSUMO DIFERIDO (COMPRA A CUOTAS) ===", &a_1};
static const cob_field c_35	= {46, (cob_u8_ptr)"ERROR: Solo tarjetas activas admiten consumos.", &a_1};
static const cob_field c_36	= {19, (cob_u8_ptr)"Estado de tarjeta: ", &a_1};
static const cob_field c_37	= {17, (cob_u8_ptr)"Tarjeta        : ", &a_1};
static const cob_field c_38	= {17, (cob_u8_ptr)"Cupo Disponible: ", &a_1};
static const cob_field c_39	= {30, (cob_u8_ptr)"Monto de compra (ej: 500.00): ", &a_1};
static const cob_field c_40	= {38, (cob_u8_ptr)"ERROR: El monto debe ser mayor a cero.", &a_1};
static const cob_field c_41	= {39, (cob_u8_ptr)"ERROR: Monto supera el cupo disponible.", &a_1};
static const cob_field c_42	= {12, (cob_u8_ptr)"Cupo libre: ", &a_1};
static const cob_field c_43	= {34, (cob_u8_ptr)"Num cuotas (1-36, 1=sin interes): ", &a_1};
static const cob_field c_44	= {39, (cob_u8_ptr)"ERROR: Cuotas invalidas. Rango: 1 a 36.", &a_1};
static const cob_field c_45	= {25, (cob_u8_ptr)"Confirmar consumo (S/N): ", &a_1};
static const cob_field c_46	= {35, (cob_u8_ptr)">>> Consumo diferido registrado <<<", &a_1};
static const cob_field c_47	= {15, (cob_u8_ptr)"Cuotas       : ", &a_1};
static const cob_field c_48	= {15, (cob_u8_ptr)"Valor cuota  : ", &a_1};
static const cob_field c_49	= {15, (cob_u8_ptr)"Monto compra : ", &a_1};
static const cob_field c_50	= {15, (cob_u8_ptr)"Interes total: ", &a_1};
static const cob_field c_51	= {15, (cob_u8_ptr)"TOTAL A PAGAR: ", &a_1};
static const cob_field c_52	= {19, (cob_u8_ptr)"ERROR en diferido: ", &a_1};
static const cob_field c_53	= {30, (cob_u8_ptr)"=== CANCELACION DE TARJETA ===", &a_1};
static const cob_field c_54	= {9, (cob_u8_ptr)"Tarjeta: ", &a_1};
static const cob_field c_55	= {9, (cob_u8_ptr)"Estado : ", &a_1};
static const cob_field c_56	= {9, (cob_u8_ptr)"Saldo  : ", &a_1};
static const cob_field c_57	= {36, (cob_u8_ptr)"ERROR: Prohibido cerrar tarjetas con", &a_1};
static const cob_field c_58	= {26, (cob_u8_ptr)"saldos pendientes de pago.", &a_1};
static const cob_field c_59	= {40, (cob_u8_ptr)"Confirmar cancelacion definitiva (S/N): ", &a_1};
static const cob_field c_60	= {39, (cob_u8_ptr)">>> Tarjeta cancelada correctamente <<<", &a_1};
static const cob_field c_61	= {42, (cob_u8_ptr)"Documento del cliente (cedula/pasaporte): ", &a_1};
static const cob_field c_62	= {44, (cob_u8_ptr)"ERROR: Documento invalido (6-12 caracteres).", &a_1};
static const cob_field c_63	= {35, (cob_u8_ptr)"ERROR: Cedula invalida (Modulo 10).", &a_1};
static const cob_field c_64	= {29, (cob_u8_ptr)"ERROR: Cliente no encontrado.", &a_1};
static const cob_field c_65	= {32, (cob_u8_ptr)"ERROR tecnico al buscar cliente.", &a_1};
static const cob_field c_66	= {9, (cob_u8_ptr)"Cliente: ", &a_1};
static const cob_field c_67	= {5, (cob_u8_ptr)"10000", &a_9};
static const cob_field c_68	= {4, (cob_u8_ptr)"4555", &a_1};
static const cob_field c_69	= {1, (cob_u8_ptr)"2", &a_10};
static const cob_field c_70	= {2, (cob_u8_ptr)"10", &a_7};
static const cob_field c_71	= {50, (cob_u8_ptr)"==================================================", &a_1};
static const cob_field c_72	= {41, (cob_u8_ptr)"     BANCO LAF - TARJETAS DE CREDITO v3.0", &a_1};
static const cob_field c_73	= {10, (cob_u8_ptr)"Operador: ", &a_1};
static const cob_field c_74	= {10, (cob_u8_ptr)"Terminal: ", &a_1};
static const cob_field c_75	= {23, (cob_u8_ptr)"1. Emitir Tarjeta Nueva", &a_1};
static const cob_field c_76	= {20, (cob_u8_ptr)"2. Consultar Tarjeta", &a_1};
static const cob_field c_77	= {18, (cob_u8_ptr)"3. Diferir Consumo", &a_1};
static const cob_field c_78	= {19, (cob_u8_ptr)"4. Cancelar Tarjeta", &a_1};
static const cob_field c_79	= {27, (cob_u8_ptr)"5. Volver al menu principal", &a_1};
static const cob_field c_80	= {50, (cob_u8_ptr)"--------------------------------------------------", &a_1};
static const cob_field c_81	= {8, (cob_u8_ptr)"Opcion: ", &a_1};

static cob_field cob_all_space	= {1, (cob_u8_ptr)" ", &cob_all_attr};
static cob_field cob_all_zero	= {1, (cob_u8_ptr)"0", &cob_all_attr};

static int COB_NOINLINE
cob_get_numdisp (const void *data, const size_t size)
{
	const unsigned char	*p;
	size_t			n;
	int    			 retval;
	p = (const unsigned char *)data;
	retval = 0;
	for (n = 0; n < size; ++n, ++p) {
		retval *= 10;
		retval += (*p & 0x0F);
	}
	return retval;
}

