/* Generated by           cobc 2.0.0 */
/* Generated from         C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
/* Generated at           may 18 2026 16:55:41 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobc.exe -C --save-temps=C:\Users\Alison\AppData\Local\Temp\cobtmp -I C:\Users\Alison\Desktop\proyecto_cobol\src\copies C:\Users\Alison\Desktop\proyecto_cobol\src\mainline\TC0000.cbl */

/* Program local variables for 'TC0000' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d0;
cob_decimal	*d1;


/* Call pointers */
cob_call_union		cob_unifunc;

/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[7];

/* Perform frame stack */
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_1;	/* RETURN-CODE */
static cob_u8_t	b_6[1] __attribute__((aligned));	/* WS-OPCION-TARJ */
static cob_u8_t	b_7[1] __attribute__((aligned));	/* WS-CONTINUAR-TARJ */
static cob_u8_t	b_8[1] __attribute__((aligned));	/* WS-CONFIRMAR */
static cob_u8_t	b_9[1] __attribute__((aligned));	/* WS-PAUSA */
static cob_u8_t	b_10[40] __attribute__((aligned));	/* WS-PROGRAMAS */
static cob_u8_t	b_16[1] __attribute__((aligned));	/* WS-ACCION-TRANS */
static cob_u8_t	b_17[12] __attribute__((aligned));	/* WS-DOC-ENTRADA */
static cob_u8_t	b_18[2] __attribute__((aligned));	/* WS-DOC-LEN */
static cob_u8_t	b_19[2] __attribute__((aligned));	/* WS-I */
static cob_u8_t	b_20[1] __attribute__((aligned));	/* WS-DOC-OK */
static cob_u8_t	b_21[1] __attribute__((aligned));	/* WS-TARJ-OK */
static cob_u8_t	b_22[3] __attribute__((aligned));	/* WS-CLS-CMD */
static cob_u8_t	b_23[12] __attribute__((aligned));	/* WS-ENTRADA-MONTO */
static cob_u8_t	b_24[3] __attribute__((aligned));	/* WS-ENTRADA-CUOTAS */
static cob_u8_t	b_25[7] __attribute__((aligned));	/* WS-MONTO-TX */
static cob_u8_t	b_26[3] __attribute__((aligned));	/* WS-CUOTAS-TX */
static cob_u8_t	b_27[8] __attribute__((aligned));	/* WS-ID-CUENTA-PRINC */
static cob_u8_t	b_28[37] __attribute__((aligned));	/* WS-CALCULOS-TC */
static cob_u8_t	b_34[8] __attribute__((aligned));	/* WS-FECHA-SISTEMA */
static cob_u8_t	b_38[4] __attribute__((aligned));	/* WS-ANIO-VENC */
static cob_u8_t	b_39[12] __attribute__((aligned));	/* WS-AUX-GEN */
static cob_u8_t	b_42[15] __attribute__((aligned));	/* WS-SALDO-EDIT */
static cob_u8_t	b_43[14] __attribute__((aligned));	/* WS-MOD10 */

/* End of data storage */


/* Fields */
static cob_field f_6	= {1, b_6, &a_10};	/* WS-OPCION-TARJ */
static cob_field f_8	= {1, b_8, &a_1};	/* WS-CONFIRMAR */
static cob_field f_9	= {1, b_9, &a_1};	/* WS-PAUSA */
static cob_field f_11	= {8, b_10, &a_1};	/* WS-PGM-DBIOCUSM */
static cob_field f_12	= {8, b_10 + 8, &a_1};	/* WS-PGM-DBIOINVM */
static cob_field f_13	= {8, b_10 + 16, &a_1};	/* WS-PGM-DBIOTARJ */
static cob_field f_14	= {8, b_10 + 24, &a_1};	/* WS-PGM-DBIOTRAN */
static cob_field f_15	= {8, b_10 + 32, &a_1};	/* WS-PGM-DF0000 */
static cob_field f_16	= {1, b_16, &a_1};	/* WS-ACCION-TRANS */
static cob_field f_17	= {12, b_17, &a_1};	/* WS-DOC-ENTRADA */
static cob_field f_19	= {2, b_19, &a_7};	/* WS-I */
static cob_field f_22	= {3, b_22, &a_1};	/* WS-CLS-CMD */
static cob_field f_23	= {12, b_23, &a_1};	/* WS-ENTRADA-MONTO */
static cob_field f_25	= {7, b_25, &a_5};	/* WS-MONTO-TX */
static cob_field f_26	= {3, b_26, &a_2};	/* WS-CUOTAS-TX */
static cob_field f_27	= {8, b_27, &a_3};	/* WS-ID-CUENTA-PRINC */
static cob_field f_29	= {7, b_28, &a_5};	/* WS-CUPO-DISPONIBLE */
static cob_field f_30	= {1, b_28 + 7, &a_1};	/* WS-RESULTADO-DIF */
static cob_field f_31	= {15, b_28 + 8, &a_8};	/* WS-CUOTA-EDIT */
static cob_field f_32	= {7, b_28 + 23, &a_5};	/* WS-TOTAL-PAGAR */
static cob_field f_33	= {7, b_28 + 30, &a_5};	/* WS-INTERES-DISP */
static cob_field f_34	= {8, b_34, &a_4};	/* WS-FECHA-SISTEMA */
static cob_field f_35	= {4, b_34, &a_6};	/* WS-ANIO */
static cob_field f_36	= {2, b_34 + 4, &a_7};	/* WS-MES */
static cob_field f_37	= {2, b_34 + 6, &a_7};	/* WS-DIA */
static cob_field f_38	= {4, b_38, &a_6};	/* WS-ANIO-VENC */
static cob_field f_40	= {8, b_39, &a_3};	/* WS-SEMILLA */
static cob_field f_41	= {4, b_39 + 8, &a_6};	/* WS-RANDOM */
static cob_field f_42	= {15, b_42, &a_8};	/* WS-SALDO-EDIT */
static cob_field f_45	= {1, b_43 + 1, &a_10};	/* WS-DIGITO */
static cob_field f_46	= {2, b_43 + 2, &a_7};	/* WS-RESULTADO */
static cob_field f_47	= {4, b_43 + 4, &a_6};	/* WS-SUMA-MOD10 */
static cob_field f_48	= {1, b_43 + 8, &a_10};	/* WS-DIGITO-VERIF */
static cob_field f_49	= {1, b_43 + 9, &a_10};	/* WS-DIGITO-CALC */
static cob_field f_50	= {2, b_43 + 10, &a_7};	/* WS-K */
static cob_field f_51	= {2, b_43 + 12, &a_7};	/* WS-PROV-DOC */
static cob_field f_52	= {210, NULL, &a_4};	/* REG-CUSM */
static cob_field f_53	= {8, NULL, &a_3};	/* CUSM-ID-CLIENTE */
static cob_field f_57	= {25, NULL, &a_1};	/* CUSM-NOMBRE-CLIENTE */
static cob_field f_58	= {25, NULL, &a_1};	/* CUSM-APELLIDOS-CLIENTE */
static cob_field f_63	= {3, NULL, &a_2};	/* CUSM-SCORE-CREDITICIO */
static cob_field f_71	= {36, NULL, &a_4};	/* REG-INVM */
static cob_field f_84	= {67, NULL, &a_4};	/* REG-TARJ */
static cob_field f_85	= {16, NULL, &a_1};	/* TARJ-NRO-TARJETA */
static cob_field f_88	= {10, NULL, &a_1};	/* TARJ-FECHA-EMISION */
static cob_field f_89	= {10, NULL, &a_1};	/* TARJ-FECHA-VENCTO */
static cob_field f_90	= {7, NULL, &a_5};	/* TARJ-CUPO-APROBADO */
static cob_field f_91	= {7, NULL, &a_5};	/* TARJ-SALDO-UTILIZADO */
static cob_field f_92	= {1, NULL, &a_1};	/* TARJ-ESTADO */
static cob_field f_96	= {47, NULL, &a_4};	/* REG-DIFD */
static cob_field f_102	= {7, NULL, &a_5};	/* DIFD-VALOR-CUOTA */
static cob_field f_104	= {86, NULL, &a_4};	/* LK-DATOS-SESION */
static cob_field f_108	= {8, NULL, &a_1};	/* LKCIF-USUARIO */
static cob_field f_109	= {4, NULL, &a_1};	/* LKCIF-TERMINAL */
static cob_field f_114	= {63, NULL, &a_4};	/* LK-DATOS-TRANSACCION */
static cob_field f_132	= {50, NULL, &a_1};	/* LK-MENSAJE */

/* End of fields */

