/* Generated by           cobc 2.0.0 */
/* Generated from         C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
/* Generated at           may 18 2026 16:55:41 */
/* GnuCOBOL build date    Nov 13 2016 01:30:50 */
/* GnuCOBOL package date  Nov 06 2016 22:36:19 UTC */
/* Compile command        C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobc.exe -C --save-temps=C:\Users\Alison\AppData\Local\Temp\cobtmp -I C:\Users\Alison\Desktop\proyecto_cobol\src\copies C:\Users\Alison\Desktop\proyecto_cobol\src\mainline\TC0000.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"may 18 2026 16:55:41"
#define  COB_MODULE_DATE		20260518
#define  COB_MODULE_TIME		165541

/* Global variables */
#include "TC0000.c.h"

/* Function prototypes */

__declspec(dllexport) int		TC0000 (cob_u8_t *, cob_u8_t *, cob_u8_t *, cob_u8_t *, cob_u8_t *, cob_u8_t *);
static int		TC0000_ (const int, cob_u8_t *, cob_u8_t *, cob_u8_t *, cob_u8_t *, cob_u8_t *, cob_u8_t *);

/* Functions */

/* PROGRAM-ID 'TC0000' */

/* ENTRY 'TC0000' */

int
TC0000 (cob_u8_t *b_52, cob_u8_t *b_71, cob_u8_t *b_84, cob_u8_t *b_96, cob_u8_t *b_104, cob_u8_t *b_114)
{
  /* Get current number of call parameters,
     if the parameter count is unknown, set it to all */
  if (cob_get_global_ptr ()->cob_current_module) {
	cob_call_params = cob_get_global_ptr ()->cob_call_params;
  } else {
	cob_call_params = 6;
  };

  return TC0000_ (0, b_52, b_71, b_84, b_96, b_104, b_114);
}

static int
TC0000_ (const int entry, cob_u8_t *b_52, cob_u8_t *b_71, 
	cob_u8_t *b_84, cob_u8_t *b_96, 
	cob_u8_t *b_104, cob_u8_t *b_114)
{
  /* Program local variables */
  #include "TC0000.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d0, &d1);

  /* Increment module active */
  module->module_active++;

  /* Set not passed parameter pointers to NULL */
  switch (cob_call_params) {
  case 0:
  	b_52 = NULL;
  case 1:
  	b_71 = NULL;
  case 2:
  	b_84 = NULL;
  case 3:
  	b_96 = NULL;
  case 4:
  	b_104 = NULL;
  case 5:
  	b_114 = NULL;
  default:
	break;
  }

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 85        : Entry     TC0000                  : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  l_2:;

  /* Line: 85        : Paragraph 0000-PRINCIPAL          : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */

  /* Line: 86        : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  *(b_7) = 83;

  /* Line: 87        : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  for (;;)
  {
    if (((int)(int)(*(b_7) - 78) == 0))
      break;
    /* PERFORM 1000-MENU-TARJ */
    frame_ptr++;
    frame_ptr->perform_through = 5;
    frame_ptr->return_address_ptr = &&l_22;
    goto l_5;
    l_22:
    frame_ptr--;
  }

  /* Line: 89        : GOBACK             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  goto exit_program;

  /* Line: 91        : Paragraph 1000-MENU-TARJ          : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  l_5:;

  /* Line: 92        : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  /* PERFORM 9050-MARCO-TARJ */
  frame_ptr++;
  frame_ptr->perform_through = 20;
  frame_ptr->return_address_ptr = &&l_23;
  goto l_20;
  l_23:
  frame_ptr--;

  /* Line: 93        : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  /* PERFORM 9051-MENU-TARJ */
  frame_ptr++;
  frame_ptr->perform_through = 21;
  frame_ptr->return_address_ptr = &&l_24;
  goto l_21;
  l_24:
  frame_ptr--;

  /* Line: 95        : EVALUATE           : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */

  /* WHEN */

  if (((int)cob_cmp_numdisp (b_6, 1, 1LL, 0) == 0))
  {

    /* Line: 97        : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    /* PERFORM 2000-EMITIR-TARJETA */
    frame_ptr++;
    frame_ptr->perform_through = 7;
    frame_ptr->return_address_ptr = &&l_25;
    goto l_7;
    l_25:
    frame_ptr--;
    goto l_6;
  }

  /* WHEN */

  if (((int)cob_cmp_numdisp (b_6, 1, 2LL, 0) == 0))
  {

    /* Line: 99        : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    /* PERFORM 3000-CONSULTAR-TARJETA */
    frame_ptr++;
    frame_ptr->perform_through = 9;
    frame_ptr->return_address_ptr = &&l_26;
    goto l_9;
    l_26:
    frame_ptr--;
    goto l_6;
  }

  /* WHEN */

  if (((int)cob_cmp_numdisp (b_6, 1, 3LL, 0) == 0))
  {

    /* Line: 101       : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    /* PERFORM 4000-CONSUMO-DIFERIDO */
    frame_ptr++;
    frame_ptr->perform_through = 11;
    frame_ptr->return_address_ptr = &&l_27;
    goto l_11;
    l_27:
    frame_ptr--;
    goto l_6;
  }

  /* WHEN */

  if (((int)cob_cmp_numdisp (b_6, 1, 4LL, 0) == 0))
  {

    /* Line: 103       : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    /* PERFORM 5000-CANCELAR-TARJETA */
    frame_ptr++;
    frame_ptr->perform_through = 13;
    frame_ptr->return_address_ptr = &&l_28;
    goto l_13;
    l_28:
    frame_ptr--;
    goto l_6;
  }

  /* WHEN */

  if (((int)cob_cmp_numdisp (b_6, 1, 5LL, 0) == 0))
  {

    /* Line: 105       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    *(b_7) = 78;
    goto l_6;
  }

  /* WHEN OTHER */

  /* Line: 107       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_1);

  /* Line: 108       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept (&f_9);

  /* End EVALUATE */
  l_6:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Line: 114       : Paragraph 2000-EMITIR-TARJETA     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  l_7:;

  /* Line: 115       : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  /* PERFORM 9050-MARCO-TARJ */
  frame_ptr++;
  frame_ptr->perform_through = 20;
  frame_ptr->return_address_ptr = &&l_29;
  goto l_20;
  l_29:
  frame_ptr--;

  /* Line: 116       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_2);

  /* Line: 118       : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  /* PERFORM 9100-BUSCAR-CLIENTE */
  frame_ptr++;
  frame_ptr->perform_through = 15;
  frame_ptr->return_address_ptr = &&l_30;
  goto l_15;
  l_30:
  frame_ptr--;

  /* Line: 119       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)(int)(*(b_20) - 78) == 0))
  {

    /* Line: 119       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_8;
  }

  /* Line: 121       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)(int)(*(b_52 + 202) - 73) == 0))
  {

    /* Line: 122       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_3);

    /* Line: 123       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 124       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 125       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_8;
  }

  /* Line: 128       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)cob_cmp_numdisp (b_52 + 190, 3, 450LL, 0) < 0))
  {

    /* Line: 129       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_5);

    /* Line: 130       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_6);

    /* Line: 131       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, COB_SET_DATA (f_63, b_52 + 190));

    /* Line: 132       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_7);

    /* Line: 133       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 134       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 135       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_8;
  }

  /* Line: 138       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)cob_cmp_numdisp (b_52 + 200, 1, 1LL, 0) == 0))
  {

    /* Line: 139       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_8);

    /* Line: 140       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_9);

    /* Line: 141       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 142       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 143       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_8;
  }

  /* Line: 146       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_10);

  /* Line: 147       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept (&f_27);

  /* Line: 149       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)cob_cmp_numdisp (b_27, 8, 0, 0) == 0))
  {

    /* Line: 150       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_11);

    /* Line: 151       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 152       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 153       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_8;
  }

  /* Line: 156       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memmove (b_71, b_27, 8);

  /* Line: 157       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memmove (b_71 + 8, b_52, 8);

  /* Line: 159       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  *(b_114) = 83;

  /* Line: 160       : CALL               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_procedure_params[0] = COB_SET_DATA (f_71, b_71);
  cob_procedure_params[1] = COB_SET_DATA (f_104, b_104);
  cob_procedure_params[2] = COB_SET_DATA (f_114, b_114);
  cob_glob_ptr->cob_call_params = 3;
  cob_unifunc.funcvoid = cob_call_field (&f_12, NULL, 1, 0);
  b_1 = ((int (*)(void *, void *, void *))cob_unifunc.funcint) (b_71, b_104, b_114);

  /* Line: 164       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)memcmp (b_114 + 9, (cob_u8_ptr)"E404", 4) == 0))
  {

    /* Line: 165       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_12);

    /* Line: 166       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 167       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 168       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_8;
  }

  /* Line: 171       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (!((int)memcmp (b_114 + 9, (cob_u8_ptr)"00  ", 4) == 0))
  {

    /* Line: 172       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, COB_SET_DATA (f_132, b_114 + 13));

    /* Line: 173       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 174       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 175       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_8;
  }

  /* Line: 178       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)(int)(*(b_71 + 35) - 65) != 0))
  {

    /* Line: 179       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_13);

    /* Line: 180       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 181       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 182       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_8;
  }

  /* Line: 185       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)(int)(*(b_71 + 16) - 72) == 0))
  {

    /* Line: 186       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_14);

    /* Line: 187       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 188       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 189       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_8;
  }

  /* Line: 192       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_15);

  /* Line: 193       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept (&f_23);

  /* Line: 195       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)cob_cmp (&f_23, &cob_all_space) == 0))
  {

    /* Line: 196       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_16);

    /* Line: 197       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 198       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 199       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_8;
  }

  /* Line: 202       : COMPUTE            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_decimal_set_field (d0, cob_intr_numval (&f_23));
  cob_decimal_get_field (d0, &f_25, 0);

  /* Line: 204       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)cob_cmp_llint (&f_25, 0) <= 0))
  {

    /* Line: 205       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_17);

    /* Line: 206       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 207       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 208       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_8;
  }

  /* Line: 211       : INITIALIZE         : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memset (b_84, 32, 16);
  memset (b_84 + 16, 48, 16);
  memset (b_84 + 32, 32, 20);
  cob_set_packed_zero (COB_SET_DATA (f_90, b_84 + 52));
  cob_set_packed_zero (COB_SET_DATA (f_91, b_84 + 59));
  *(cob_u8_ptr)(b_84 + 66) = 32;

  /* Line: 212       : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  /* PERFORM 9200-GENERAR-NRO-TARJETA */
  frame_ptr++;
  frame_ptr->perform_through = 17;
  frame_ptr->return_address_ptr = &&l_31;
  goto l_17;
  l_31:
  frame_ptr--;

  /* Line: 214       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept_date_yyyymmdd (&f_34);

  /* Line: 215       : ADD                : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_decimal_set_llint (d0, 5LL);
  cob_decimal_set_field (d1, &f_35);
  cob_decimal_add (d0, d1);
  cob_decimal_get_field (d0, &f_38, 0);

  /* Line: 217       : STRING             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_string_init (COB_SET_DATA (f_88, b_84 + 32), NULL);
  cob_string_delimited (NULL);
  cob_string_append (&f_35);
  cob_string_append ((cob_field *)&c_18);
  cob_string_append (&f_36);
  cob_string_append ((cob_field *)&c_18);
  cob_string_append (&f_37);
  cob_string_finish ();

  /* Line: 220       : STRING             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_string_init (COB_SET_DATA (f_89, b_84 + 42), NULL);
  cob_string_delimited (NULL);
  cob_string_append (&f_38);
  cob_string_append ((cob_field *)&c_18);
  cob_string_append (&f_36);
  cob_string_append ((cob_field *)&c_18);
  cob_string_append (&f_37);
  cob_string_finish ();

  /* Line: 224       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memmove (b_84 + 16, b_52, 8);

  /* Line: 225       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memmove (b_84 + 24, b_27, 8);

  /* Line: 226       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memmove (b_84 + 52, b_25, 7);

  /* Line: 227       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_set_packed_zero (COB_SET_DATA (f_91, b_84 + 59));

  /* Line: 228       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  *(b_84 + 66) = 65;

  /* Line: 230       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  *(b_114) = 65;

  /* Line: 231       : CALL               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_procedure_params[0] = COB_SET_DATA (f_84, b_84);
  cob_procedure_params[1] = COB_SET_DATA (f_96, b_96);
  cob_procedure_params[2] = COB_SET_DATA (f_104, b_104);
  cob_procedure_params[3] = COB_SET_DATA (f_114, b_114);
  cob_glob_ptr->cob_call_params = 4;
  cob_unifunc.funcvoid = cob_call_field (&f_13, NULL, 1, 0);
  b_1 = ((int (*)(void *, void *, void *, void *))cob_unifunc.funcint) (b_84, b_96, b_104, b_114);

  /* Line: 236       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)memcmp (b_114 + 9, (cob_u8_ptr)"00  ", 4) == 0))
  {

    /* Line: 237       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    *(b_16) = 67;

    /* Line: 238       : CALL               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_procedure_params[0] = &f_16;
    cob_glob_ptr->cob_call_params = 1;
    cob_unifunc.funcvoid = cob_call_field (&f_14, NULL, 1, 0);
    b_1 = ((int (*)(void *))cob_unifunc.funcint) (b_16);

    /* Line: 239       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_move (&f_25, &f_42);

    /* Line: 240       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_19);

    /* Line: 241       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_20);

    /* Line: 242       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, COB_SET_DATA (f_85, b_84));

    /* Line: 243       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_21);

    /* Line: 244       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, COB_SET_DATA (f_89, b_84 + 42));

    /* Line: 245       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_22);

    /* Line: 246       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &f_42);
  }
  else
  {
    /* ELSE */

    /* Line: 248       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    *(b_16) = 82;

    /* Line: 249       : CALL               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_procedure_params[0] = &f_16;
    cob_glob_ptr->cob_call_params = 1;
    cob_unifunc.funcvoid = cob_call_field (&f_14, NULL, 1, 0);
    b_1 = ((int (*)(void *))cob_unifunc.funcint) (b_16);

    /* Line: 250       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    if (((int)memcmp (b_114 + 9, (cob_u8_ptr)"E409", 4) == 0))
    {

      /* Line: 251       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
      cob_display (0, 1, 1, &c_23);
    }
    else
    {
      /* ELSE */

      /* Line: 253       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
      cob_display (0, 1, 1, COB_SET_DATA (f_132, b_114 + 13));
    }
  }

  /* Line: 257       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_4);

  /* Line: 258       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept (&f_9);

  /* Implicit EXIT label */
  l_8:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 7)
    goto *frame_ptr->return_address_ptr;

  /* Line: 263       : Paragraph 3000-CONSULTAR-TARJETA  : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  l_9:;

  /* Line: 264       : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  /* PERFORM 9050-MARCO-TARJ */
  frame_ptr++;
  frame_ptr->perform_through = 20;
  frame_ptr->return_address_ptr = &&l_32;
  goto l_20;
  l_32:
  frame_ptr--;

  /* Line: 265       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_24);

  /* Line: 267       : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  /* PERFORM 9100-BUSCAR-CLIENTE */
  frame_ptr++;
  frame_ptr->perform_through = 15;
  frame_ptr->return_address_ptr = &&l_33;
  goto l_15;
  l_33:
  frame_ptr--;

  /* Line: 268       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)(int)(*(b_20) - 78) == 0))
  {

    /* Line: 268       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_10;
  }

  /* Line: 270       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memmove (b_84 + 16, b_52, 8);

  /* Line: 272       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  *(b_114) = 67;

  /* Line: 273       : CALL               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_procedure_params[0] = COB_SET_DATA (f_84, b_84);
  cob_procedure_params[1] = COB_SET_DATA (f_96, b_96);
  cob_procedure_params[2] = COB_SET_DATA (f_104, b_104);
  cob_procedure_params[3] = COB_SET_DATA (f_114, b_114);
  cob_glob_ptr->cob_call_params = 4;
  cob_unifunc.funcvoid = cob_call_field (&f_13, NULL, 1, 0);
  b_1 = ((int (*)(void *, void *, void *, void *))cob_unifunc.funcint) (b_84, b_96, b_104, b_114);

  /* Line: 278       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)memcmp (b_114 + 9, (cob_u8_ptr)"E404", 4) == 0))
  {

    /* Line: 279       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_25);

    /* Line: 280       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 281       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 282       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_10;
  }

  /* Line: 285       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (!((int)memcmp (b_114 + 9, (cob_u8_ptr)"00  ", 4) == 0))
  {

    /* Line: 286       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, COB_SET_DATA (f_132, b_114 + 13));

    /* Line: 287       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 288       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 289       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_10;
  }

  /* Line: 292       : COMPUTE            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_decimal_set_field (d0, COB_SET_DATA (f_90, b_84 + 52));
  cob_decimal_set_field (d1, COB_SET_DATA (f_91, b_84 + 59));
  cob_decimal_sub (d0, d1);
  cob_decimal_get_field (d0, &f_29, 0);

  /* Line: 295       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_26);

  /* Line: 296       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_27);

  /* Line: 297       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, COB_SET_DATA (f_85, b_84));

  /* Line: 298       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_28);

  /* Line: 299       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, COB_SET_DATA (f_92, b_84 + 66));

  /* Line: 300       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_29);

  /* Line: 301       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, COB_SET_DATA (f_88, b_84 + 32));

  /* Line: 302       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_30);

  /* Line: 303       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, COB_SET_DATA (f_89, b_84 + 42));

  /* Line: 304       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_26);

  /* Line: 305       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_move (COB_SET_DATA (f_90, b_84 + 52), &f_42);

  /* Line: 306       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_31);

  /* Line: 307       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &f_42);

  /* Line: 308       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_move (COB_SET_DATA (f_91, b_84 + 59), &f_42);

  /* Line: 309       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_32);

  /* Line: 310       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &f_42);

  /* Line: 311       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_move (&f_29, &f_42);

  /* Line: 312       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_33);

  /* Line: 313       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &f_42);

  /* Line: 314       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_26);

  /* Line: 316       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_4);

  /* Line: 317       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept (&f_9);

  /* Implicit EXIT label */
  l_10:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Line: 322       : Paragraph 4000-CONSUMO-DIFERIDO   : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  l_11:;

  /* Line: 323       : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  /* PERFORM 9050-MARCO-TARJ */
  frame_ptr++;
  frame_ptr->perform_through = 20;
  frame_ptr->return_address_ptr = &&l_34;
  goto l_20;
  l_34:
  frame_ptr--;

  /* Line: 324       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_34);

  /* Line: 326       : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  /* PERFORM 9100-BUSCAR-CLIENTE */
  frame_ptr++;
  frame_ptr->perform_through = 15;
  frame_ptr->return_address_ptr = &&l_35;
  goto l_15;
  l_35:
  frame_ptr--;

  /* Line: 327       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)(int)(*(b_20) - 78) == 0))
  {

    /* Line: 327       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_12;
  }

  /* Line: 329       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)(int)(*(b_52 + 202) - 73) == 0))
  {

    /* Line: 330       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_3);

    /* Line: 331       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 332       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 333       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_12;
  }

  /* Line: 336       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memmove (b_84 + 16, b_52, 8);

  /* Line: 338       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  *(b_114) = 67;

  /* Line: 339       : CALL               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_procedure_params[0] = COB_SET_DATA (f_84, b_84);
  cob_procedure_params[1] = COB_SET_DATA (f_96, b_96);
  cob_procedure_params[2] = COB_SET_DATA (f_104, b_104);
  cob_procedure_params[3] = COB_SET_DATA (f_114, b_114);
  cob_glob_ptr->cob_call_params = 4;
  cob_unifunc.funcvoid = cob_call_field (&f_13, NULL, 1, 0);
  b_1 = ((int (*)(void *, void *, void *, void *))cob_unifunc.funcint) (b_84, b_96, b_104, b_114);

  /* Line: 344       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)memcmp (b_114 + 9, (cob_u8_ptr)"E404", 4) == 0))
  {

    /* Line: 345       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_25);

    /* Line: 346       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 347       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 348       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_12;
  }

  /* Line: 351       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (!((int)memcmp (b_114 + 9, (cob_u8_ptr)"00  ", 4) == 0))
  {

    /* Line: 352       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, COB_SET_DATA (f_132, b_114 + 13));

    /* Line: 353       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 354       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 355       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_12;
  }

  /* Line: 358       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (!((int)(int)(*(b_84 + 66) - 65) == 0))
  {

    /* Line: 359       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_35);

    /* Line: 360       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_36);

    /* Line: 361       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, COB_SET_DATA (f_92, b_84 + 66));

    /* Line: 362       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 363       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 364       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_12;
  }

  /* Line: 367       : COMPUTE            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_decimal_set_field (d0, COB_SET_DATA (f_90, b_84 + 52));
  cob_decimal_set_field (d1, COB_SET_DATA (f_91, b_84 + 59));
  cob_decimal_sub (d0, d1);
  cob_decimal_get_field (d0, &f_29, 0);

  /* Line: 369       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_move (&f_29, &f_42);

  /* Line: 371       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_37);

  /* Line: 372       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, COB_SET_DATA (f_85, b_84));

  /* Line: 373       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_38);

  /* Line: 374       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &f_42);

  /* Line: 376       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_39);

  /* Line: 377       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept (&f_23);

  /* Line: 379       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)cob_cmp (&f_23, &cob_all_space) == 0))
  {

    /* Line: 380       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_16);

    /* Line: 381       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 382       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 383       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_12;
  }

  /* Line: 386       : COMPUTE            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_decimal_set_field (d0, cob_intr_numval (&f_23));
  cob_decimal_get_field (d0, &f_25, 0);

  /* Line: 388       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)cob_cmp_llint (&f_25, 0) <= 0))
  {

    /* Line: 389       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_40);

    /* Line: 390       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 391       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 392       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_12;
  }

  /* Line: 395       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)cob_cmp (&f_25, &f_29) > 0))
  {

    /* Line: 396       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_move (&f_29, &f_42);

    /* Line: 397       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_41);

    /* Line: 398       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_42);

    /* Line: 399       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &f_42);

    /* Line: 400       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 401       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 402       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_12;
  }

  /* Line: 405       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memset (b_26, 48, 3);

  /* Line: 406       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_43);

  /* Line: 407       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept (&f_26);

  /* Line: 409       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if ((((int)cob_cmp_numdisp (b_26, 3, 1LL, 0) < 0) || 
      ((int)cob_cmp_numdisp (b_26, 3, 36LL, 0) > 0)))
  {

    /* Line: 410       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_44);

    /* Line: 411       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 412       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 413       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_12;
  }

  /* Line: 416       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_45);

  /* Line: 417       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept (&f_8);

  /* Line: 419       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if ((((int)(int)(*(b_8) - 83) != 0) && 
      ((int)(int)(*(b_8) - 115) != 0)))
  {

    /* Line: 420       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_16);

    /* Line: 421       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 422       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 423       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_12;
  }

  /* Line: 427       : CALL               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_procedure_params[0] = COB_SET_DATA (f_84, b_84);
  cob_procedure_params[1] = COB_SET_DATA (f_96, b_96);
  cob_procedure_params[2] = COB_SET_DATA (f_104, b_104);
  cob_procedure_params[3] = COB_SET_DATA (f_114, b_114);
  cob_procedure_params[4] = &f_25;
  cob_procedure_params[5] = &f_26;
  cob_procedure_params[6] = &f_30;
  cob_glob_ptr->cob_call_params = 7;
  cob_unifunc.funcvoid = cob_call_field (&f_15, NULL, 1, 0);
  b_1 = ((int (*)(void *, void *, void *, void *, void *, void *, void *))cob_unifunc.funcint) (b_84, b_96, b_104, b_114, b_25, b_26, b_28 + 7);

  /* Line: 435       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)(int)(*(b_28 + 7) - 83) == 0))
  {

    /* Line: 436       : COMPUTE            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_decimal_set_field (d0, COB_SET_DATA (f_102, b_96 + 37));
    cob_decimal_set_field (d1, &f_26);
    cob_decimal_mul (d0, d1);
    cob_decimal_get_field (d0, &f_32, 0);

    /* Line: 438       : COMPUTE            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_decimal_set_field (d0, &f_32);
    cob_decimal_set_field (d1, &f_25);
    cob_decimal_sub (d0, d1);
    cob_decimal_get_field (d0, &f_33, 0);

    /* Line: 440       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_move (COB_SET_DATA (f_102, b_96 + 37), &f_31);

    /* Line: 441       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_46);

    /* Line: 442       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_47);

    /* Line: 443       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &f_26);

    /* Line: 444       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_48);

    /* Line: 445       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &f_31);

    /* Line: 446       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_move (&f_25, &f_42);

    /* Line: 447       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_49);

    /* Line: 448       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &f_42);

    /* Line: 449       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_move (&f_33, &f_42);

    /* Line: 450       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_50);

    /* Line: 451       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &f_42);

    /* Line: 452       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_move (&f_32, &f_42);

    /* Line: 453       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_51);

    /* Line: 454       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &f_42);
  }
  else
  {
    /* ELSE */

    /* Line: 456       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_52);

    /* Line: 457       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, COB_SET_DATA (f_132, b_114 + 13));
  }

  /* Line: 460       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_4);

  /* Line: 461       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept (&f_9);

  /* Implicit EXIT label */
  l_12:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 11)
    goto *frame_ptr->return_address_ptr;

  /* Line: 466       : Paragraph 5000-CANCELAR-TARJETA   : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  l_13:;

  /* Line: 467       : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  /* PERFORM 9050-MARCO-TARJ */
  frame_ptr++;
  frame_ptr->perform_through = 20;
  frame_ptr->return_address_ptr = &&l_36;
  goto l_20;
  l_36:
  frame_ptr--;

  /* Line: 468       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_53);

  /* Line: 470       : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  /* PERFORM 9100-BUSCAR-CLIENTE */
  frame_ptr++;
  frame_ptr->perform_through = 15;
  frame_ptr->return_address_ptr = &&l_37;
  goto l_15;
  l_37:
  frame_ptr--;

  /* Line: 471       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)(int)(*(b_20) - 78) == 0))
  {

    /* Line: 471       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_14;
  }

  /* Line: 473       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memmove (b_84 + 16, b_52, 8);

  /* Line: 475       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  *(b_114) = 67;

  /* Line: 476       : CALL               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_procedure_params[0] = COB_SET_DATA (f_84, b_84);
  cob_procedure_params[1] = COB_SET_DATA (f_96, b_96);
  cob_procedure_params[2] = COB_SET_DATA (f_104, b_104);
  cob_procedure_params[3] = COB_SET_DATA (f_114, b_114);
  cob_glob_ptr->cob_call_params = 4;
  cob_unifunc.funcvoid = cob_call_field (&f_13, NULL, 1, 0);
  b_1 = ((int (*)(void *, void *, void *, void *))cob_unifunc.funcint) (b_84, b_96, b_104, b_114);

  /* Line: 481       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)memcmp (b_114 + 9, (cob_u8_ptr)"E404", 4) == 0))
  {

    /* Line: 482       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_25);

    /* Line: 483       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 484       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 485       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_14;
  }

  /* Line: 488       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (!((int)memcmp (b_114 + 9, (cob_u8_ptr)"00  ", 4) == 0))
  {

    /* Line: 489       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, COB_SET_DATA (f_132, b_114 + 13));

    /* Line: 490       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 491       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 492       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_14;
  }

  /* Line: 495       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_move (COB_SET_DATA (f_91, b_84 + 59), &f_42);

  /* Line: 496       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_26);

  /* Line: 497       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_54);

  /* Line: 498       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, COB_SET_DATA (f_85, b_84));

  /* Line: 499       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_55);

  /* Line: 500       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, COB_SET_DATA (f_92, b_84 + 66));

  /* Line: 501       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_56);

  /* Line: 502       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &f_42);

  /* Line: 503       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_26);

  /* Line: 505       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)cob_cmp_llint (COB_SET_DATA (f_91, b_84 + 59), 0) > 0))
  {

    /* Line: 506       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_57);

    /* Line: 507       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_58);

    /* Line: 508       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 509       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 510       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_14;
  }

  /* Line: 513       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_59);

  /* Line: 514       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept (&f_8);

  /* Line: 516       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if ((((int)(int)(*(b_8) - 83) != 0) && 
      ((int)(int)(*(b_8) - 115) != 0)))
  {

    /* Line: 517       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_16);

    /* Line: 518       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 519       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 520       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_14;
  }

  /* Line: 523       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  *(b_114) = 66;

  /* Line: 524       : CALL               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_procedure_params[0] = COB_SET_DATA (f_84, b_84);
  cob_procedure_params[1] = COB_SET_DATA (f_96, b_96);
  cob_procedure_params[2] = COB_SET_DATA (f_104, b_104);
  cob_procedure_params[3] = COB_SET_DATA (f_114, b_114);
  cob_glob_ptr->cob_call_params = 4;
  cob_unifunc.funcvoid = cob_call_field (&f_13, NULL, 1, 0);
  b_1 = ((int (*)(void *, void *, void *, void *))cob_unifunc.funcint) (b_84, b_96, b_104, b_114);

  /* Line: 529       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)memcmp (b_114 + 9, (cob_u8_ptr)"00  ", 4) == 0))
  {

    /* Line: 530       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    *(b_16) = 67;

    /* Line: 531       : CALL               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_procedure_params[0] = &f_16;
    cob_glob_ptr->cob_call_params = 1;
    cob_unifunc.funcvoid = cob_call_field (&f_14, NULL, 1, 0);
    b_1 = ((int (*)(void *))cob_unifunc.funcint) (b_16);

    /* Line: 532       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_60);
  }
  else
  {
    /* ELSE */

    /* Line: 534       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    *(b_16) = 82;

    /* Line: 535       : CALL               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_procedure_params[0] = &f_16;
    cob_glob_ptr->cob_call_params = 1;
    cob_unifunc.funcvoid = cob_call_field (&f_14, NULL, 1, 0);
    b_1 = ((int (*)(void *))cob_unifunc.funcint) (b_16);

    /* Line: 536       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, COB_SET_DATA (f_132, b_114 + 13));
  }

  /* Line: 539       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_4);

  /* Line: 540       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept (&f_9);

  /* Implicit EXIT label */
  l_14:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 13)
    goto *frame_ptr->return_address_ptr;

  /* Line: 545       : Paragraph 9100-BUSCAR-CLIENTE     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  l_15:;

  /* Line: 546       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  *(b_20) = 78;

  /* Line: 547       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_61);

  /* Line: 548       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept (&f_17);

  /* Line: 550       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memcpy (b_19, "12", 2);

  /* Line: 551       : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  for (;;)
  {
    if ((((int)cob_cmp_numdisp (b_19, 2, 0LL, 0) == 0) || 
        ((int)(int)(*(b_17 + (cob_get_numdisp (b_19, 2) - 1)) - ' ') != 0)))
      break;

    /* Line: 553       : SUBTRACT           : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_sub_int (&f_19, 1, 0);
  }

  /* Line: 555       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memcpy (b_18, b_19, 2);

  /* Line: 557       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if ((((int)cob_cmp_numdisp (b_18, 2, 6LL, 0) < 0) || 
      ((int)cob_cmp_numdisp (b_18, 2, 12LL, 0) > 0)))
  {

    /* Line: 558       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_62);

    /* Line: 559       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 560       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 561       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_16;
  }

  /* Line: 564       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)cob_cmp_numdisp (b_18, 2, 10LL, 0) == 0))
  {

    /* Line: 565       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    if (cob_is_numeric (COB_SET_FLD(f0, 10, b_17 + 0, &a_1)))
    {

      /* Line: 566       : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
      /* PERFORM 9800-VALIDAR-MODULO-10 */
      frame_ptr++;
      frame_ptr->perform_through = 18;
      frame_ptr->return_address_ptr = &&l_38;
      goto l_18;
      l_38:
      frame_ptr--;

      /* Line: 567       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
      if (((int)(int)(*(b_43) - 78) == 0))
      {

        /* Line: 568       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
        cob_display (0, 1, 1, &c_63);

        /* Line: 569       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
        cob_display (0, 1, 1, &c_4);

        /* Line: 570       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
        cob_accept (&f_9);

        /* Line: 571       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
        goto l_16;
      }

      /* Line: 573       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
      memcpy (b_52 + 8, "CED", 3);
    }
    else
    {
      /* ELSE */

      /* Line: 575       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
      memcpy (b_52 + 8, "PAS", 3);
    }
  }
  else
  {
    /* ELSE */

    /* Line: 578       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    memcpy (b_52 + 8, "PAS", 3);
  }

  /* Line: 581       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memmove (b_52 + 11, b_17, 12);

  /* Line: 583       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  *(b_114) = 67;

  /* Line: 584       : CALL               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_procedure_params[0] = COB_SET_DATA (f_52, b_52);
  cob_procedure_params[1] = COB_SET_DATA (f_104, b_104);
  cob_procedure_params[2] = COB_SET_DATA (f_114, b_114);
  cob_glob_ptr->cob_call_params = 3;
  cob_unifunc.funcvoid = cob_call_field (&f_11, NULL, 1, 0);
  b_1 = ((int (*)(void *, void *, void *))cob_unifunc.funcint) (b_52, b_104, b_114);

  /* Line: 588       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)memcmp (b_114 + 9, (cob_u8_ptr)"E404", 4) == 0))
  {

    /* Line: 589       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_64);

    /* Line: 590       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 591       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 592       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_16;
  }

  /* Line: 595       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (!((int)memcmp (b_114 + 9, (cob_u8_ptr)"00  ", 4) == 0))
  {

    /* Line: 596       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_65);

    /* Line: 597       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_display (0, 1, 1, &c_4);

    /* Line: 598       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_accept (&f_9);

    /* Line: 599       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_16;
  }

  /* Line: 602       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_66);

  /* Line: 603       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, COB_SET_DATA (f_57, b_52 + 33));

  /* Line: 604       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, COB_SET_DATA (f_58, b_52 + 58));

  /* Line: 605       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  *(b_20) = 83;

  /* Implicit EXIT label */
  l_16:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 15)
    goto *frame_ptr->return_address_ptr;

  /* Line: 610       : Paragraph 9200-GENERAR-NRO-TARJETA: C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  l_17:;

  /* Line: 611       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept_time (&f_40);

  /* Line: 612       : COMPUTE            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_decimal_set_field (d0, cob_intr_mod (&f_40, (cob_field *)&c_67));
  cob_decimal_get_field (d0, &f_41, 0);

  /* Line: 613       : STRING             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_string_init (COB_SET_DATA (f_85, b_84), NULL);
  cob_string_delimited (NULL);
  cob_string_append ((cob_field *)&c_68);
  cob_string_append (COB_SET_DATA (f_53, b_52));
  cob_string_append (&f_41);
  cob_string_finish ();

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 17)
    goto *frame_ptr->return_address_ptr;

  /* Line: 620       : Paragraph 9800-VALIDAR-MODULO-10  : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  l_18:;

  /* Line: 621       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  *(b_43) = 78;

  /* Line: 622       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memset (b_43 + 4, 48, 4);

  /* Line: 624       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_move (COB_SET_FLD(f0, 2, b_17 + 0, &a_1), &f_51);

  /* Line: 625       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if ((((int)cob_cmp_numdisp (b_43 + 12, 2, 1LL, 0) < 0) || 
      ((int)cob_cmp_numdisp (b_43 + 12, 2, 24LL, 0) > 0)))
  {

    /* Line: 626       : EXIT PARAGRAPH     : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    goto l_19;
  }

  /* Line: 629       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_move (COB_SET_FLD(f0, 1, b_17 + 9, &a_1), &f_48);

  /* Line: 631       : PERFORM            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  memcpy (b_43 + 10, "01", 2);
  for (;;)
  {
    if (((int)cob_cmp_numdisp (b_43 + 10, 2, 9LL, 0) > 0))
      break;

    /* Line: 633       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_move (COB_SET_FLD(f0, 1, b_17 + (cob_get_numdisp (b_43 + 10, 2) - 1), &a_1), &f_45);

    /* Line: 634       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    if (((int)cob_cmp_llint (cob_intr_mod (&f_50, (cob_field *)&c_69), 1LL) == 0))
    {

      /* Line: 635       : COMPUTE            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
      cob_decimal_set_field (d0, &f_45);
      cob_decimal_set_llint (d1, 2LL);
      cob_decimal_mul (d0, d1);
      cob_decimal_get_field (d0, &f_46, 0);

      /* Line: 636       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
      if (((int)cob_cmp_numdisp (b_43 + 2, 2, 10LL, 0) >= 0))
      {

        /* Line: 637       : SUBTRACT           : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
        cob_sub_int (&f_46, 9, 0);
      }
    }
    else
    {
      /* ELSE */

      /* Line: 640       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
      cob_move (&f_45, &f_46);
    }

    /* Line: 642       : ADD                : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_add_int (&f_47, cob_get_numdisp (b_43 + 2, 2), 0);
    cob_add_int (&f_50, 1, 0);
  }

  /* Line: 645       : COMPUTE            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_decimal_set_field (d0, cob_intr_mod (&f_47, (cob_field *)&c_70));
  cob_decimal_get_field (d0, &f_49, 0);

  /* Line: 648       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)cob_cmp_numdisp (b_43 + 9, 1, 0LL, 0) != 0))
  {

    /* Line: 649       : COMPUTE            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    cob_decimal_set_llint (d0, 10LL);
    cob_decimal_set_field (d1, &f_49);
    cob_decimal_sub (d0, d1);
    cob_decimal_get_field (d0, &f_49, 0);
  }

  /* Line: 652       : IF                 : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  if (((int)memcmp (b_43 + 9, b_43 + 8, 1) == 0))
  {

    /* Line: 653       : MOVE               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
    *(b_43) = 83;
  }

  /* Implicit EXIT label */
  l_19:;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 18)
    goto *frame_ptr->return_address_ptr;

  /* Line: 659       : Paragraph 9050-MARCO-TARJ         : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  l_20:;

  /* Line: 660       : CALL               : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_procedure_params[0] = &f_22;
  cob_glob_ptr->cob_call_params = 1;
  b_1 = cob_sys_system (b_22);

  /* Line: 661       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_71);

  /* Line: 662       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_72);

  /* Line: 663       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_71);

  /* Line: 664       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_73);

  /* Line: 665       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, COB_SET_DATA (f_108, b_104 + 70));

  /* Line: 666       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_74);

  /* Line: 667       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, COB_SET_DATA (f_109, b_104 + 78));

  /* Line: 668       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_71);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 20)
    goto *frame_ptr->return_address_ptr;

  /* Line: 673       : Paragraph 9051-MENU-TARJ          : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  l_21:;

  /* Line: 674       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_75);

  /* Line: 675       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_76);

  /* Line: 676       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_77);

  /* Line: 677       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_78);

  /* Line: 678       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_79);

  /* Line: 679       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_80);

  /* Line: 680       : DISPLAY            : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_display (0, 1, 1, &c_81);

  /* Line: 681       : ACCEPT             : C:/Users/Alison/Desktop/proyecto_cobol/src/mainline/TC0000.cbl */
  cob_accept (&f_6);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 21)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  exit_program:

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_1;

  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  /* Initialize module structure */
  module->module_name = "TC0000";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())TC0000;
  module->module_cancel.funcptr = (void *(*)())TC0000_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 6;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_1 = 0;
  *(cob_u8_ptr)(b_6) = 48;
  *(cob_u8_ptr)(b_7) = 83;
  *(cob_u8_ptr)(b_8) = 32;
  *(cob_u8_ptr)(b_9) = 32;
  memcpy (b_10, "DBIOCUSM", 8);
  memcpy (b_10 + 8, "DBIOINVM", 8);
  memcpy (b_10 + 16, "DBIOTARJ", 8);
  memcpy (b_10 + 24, "DBIOTRAN", 8);
  memcpy (b_10 + 32, "DF0000  ", 8);
  *(cob_u8_ptr)(b_16) = 32;
  memset (b_17, 32, 12);
  memset (b_18, 48, 2);
  memset (b_19, 48, 2);
  *(cob_u8_ptr)(b_20) = 78;
  *(cob_u8_ptr)(b_21) = 78;
  memcpy (b_22, "cls", 3);
  memset (b_23, 32, 12);
  memset (b_24, 32, 3);
  cob_set_packed_zero (&f_25);
  memset (b_26, 48, 3);
  memset (b_27, 48, 8);
  cob_set_packed_zero (&f_29);
  *(cob_u8_ptr)(b_28 + 7) = 32;
  cob_move (&cob_all_zero, &f_31);
  cob_set_packed_zero (&f_32);
  cob_set_packed_zero (&f_33);
  memset (b_34, 48, 8);
  memset (b_38, 48, 4);
  memset (b_39, 48, 12);
  cob_move (&cob_all_zero, &f_42);
  *(cob_u8_ptr)(b_43) = 78;
  memset (b_43 + 1, 48, 3);
  memset (b_43 + 4, 48, 4);
  memset (b_43 + 8, 48, 6);

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  b_1 = 0;
  cob_cache_free (module);
  module = NULL;

  initialized = 0;
  return 0;

}

/* End PROGRAM-ID 'TC0000' */

/* End functions */

